# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/max/github/dermochelys/acidwarp-android/app/jni/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/max/github/dermochelys/acidwarp-android/app/jni/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/github/dermochelys/acidwarp-android/app/jni/src/CMakeFiles /home/max/github/dermochelys/acidwarp-android/app/jni/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/github/dermochelys/acidwarp-android/app/jni/src/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/github/dermochelys/acidwarp-android/app/jni/src/CMakeFiles /home/max/github/dermochelys/acidwarp-android/app/jni/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/github/dermochelys/acidwarp-android/app/jni/src/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

acidwarp.o: acidwarp.c.o
.PHONY : acidwarp.o

# target to build an object file
acidwarp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/acidwarp.c.o
.PHONY : acidwarp.c.o

acidwarp.i: acidwarp.c.i
.PHONY : acidwarp.i

# target to preprocess a source file
acidwarp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/acidwarp.c.i
.PHONY : acidwarp.c.i

acidwarp.s: acidwarp.c.s
.PHONY : acidwarp.s

# target to generate assembly for a file
acidwarp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/acidwarp.c.s
.PHONY : acidwarp.c.s

bit_map.o: bit_map.c.o
.PHONY : bit_map.o

# target to build an object file
bit_map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bit_map.c.o
.PHONY : bit_map.c.o

bit_map.i: bit_map.c.i
.PHONY : bit_map.i

# target to preprocess a source file
bit_map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bit_map.c.i
.PHONY : bit_map.c.i

bit_map.s: bit_map.c.s
.PHONY : bit_map.s

# target to generate assembly for a file
bit_map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bit_map.c.s
.PHONY : bit_map.c.s

display.o: display.c.o
.PHONY : display.o

# target to build an object file
display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/display.c.o
.PHONY : display.c.o

display.i: display.c.i
.PHONY : display.i

# target to preprocess a source file
display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/display.c.i
.PHONY : display.c.i

display.s: display.c.s
.PHONY : display.s

# target to generate assembly for a file
display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/display.c.s
.PHONY : display.c.s

draw.o: draw.c.o
.PHONY : draw.o

# target to build an object file
draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/draw.c.o
.PHONY : draw.c.o

draw.i: draw.c.i
.PHONY : draw.i

# target to preprocess a source file
draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/draw.c.i
.PHONY : draw.c.i

draw.s: draw.c.s
.PHONY : draw.s

# target to generate assembly for a file
draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/draw.c.s
.PHONY : draw.c.s

gen_img.o: gen_img.c.o
.PHONY : gen_img.o

# target to build an object file
gen_img.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gen_img.c.o
.PHONY : gen_img.c.o

gen_img.i: gen_img.c.i
.PHONY : gen_img.i

# target to preprocess a source file
gen_img.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gen_img.c.i
.PHONY : gen_img.c.i

gen_img.s: gen_img.c.s
.PHONY : gen_img.s

# target to generate assembly for a file
gen_img.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gen_img.c.s
.PHONY : gen_img.c.s

img_float.o: img_float.c.o
.PHONY : img_float.o

# target to build an object file
img_float.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/img_float.c.o
.PHONY : img_float.c.o

img_float.i: img_float.c.i
.PHONY : img_float.i

# target to preprocess a source file
img_float.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/img_float.c.i
.PHONY : img_float.c.i

img_float.s: img_float.c.s
.PHONY : img_float.s

# target to generate assembly for a file
img_float.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/img_float.c.s
.PHONY : img_float.c.s

palinit.o: palinit.c.o
.PHONY : palinit.o

# target to build an object file
palinit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/palinit.c.o
.PHONY : palinit.c.o

palinit.i: palinit.c.i
.PHONY : palinit.i

# target to preprocess a source file
palinit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/palinit.c.i
.PHONY : palinit.c.i

palinit.s: palinit.c.s
.PHONY : palinit.s

# target to generate assembly for a file
palinit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/palinit.c.s
.PHONY : palinit.c.s

rolnfade.o: rolnfade.c.o
.PHONY : rolnfade.o

# target to build an object file
rolnfade.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/rolnfade.c.o
.PHONY : rolnfade.c.o

rolnfade.i: rolnfade.c.i
.PHONY : rolnfade.i

# target to preprocess a source file
rolnfade.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/rolnfade.c.i
.PHONY : rolnfade.c.i

rolnfade.s: rolnfade.c.s
.PHONY : rolnfade.s

# target to generate assembly for a file
rolnfade.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/rolnfade.c.s
.PHONY : rolnfade.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... acidwarp.o"
	@echo "... acidwarp.i"
	@echo "... acidwarp.s"
	@echo "... bit_map.o"
	@echo "... bit_map.i"
	@echo "... bit_map.s"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... gen_img.o"
	@echo "... gen_img.i"
	@echo "... gen_img.s"
	@echo "... img_float.o"
	@echo "... img_float.i"
	@echo "... img_float.s"
	@echo "... palinit.o"
	@echo "... palinit.i"
	@echo "... palinit.s"
	@echo "... rolnfade.o"
	@echo "... rolnfade.i"
	@echo "... rolnfade.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

